name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      working-directory: ./core/build
      run: |
        sed -i -e "s|PLATFORM *= *[A-Z]*|PLATFORM = LINUX|g" makefile
        sed -i -e "s|HARDWARE_ACCEL *= *[A-Z]*|HARDWARE_ACCEL = OMP|g" makefile
        sed -i -e "s|VBITS *= *[0-9]*|VBITS = 256|g" makefile
        sed -i -e "s|ENDIANNESS *= *[A-Z]*|ENDIANNESS = LITTLE|g" makefile
        sed -i -e "s|COMPILER_PREF *= *[A-Z]*|COMPILER_PREF = GNU|g" makefile
    - name: make
      working-directory: ./core/build
      run: make tw3d_debug
    - name: turbowave unit testing
      working-directory: ./core/build
      run: ./tw3d -n 2 --unit-test --all
